"""add vendor to expense

Revision ID: 5b8360c35958
Revises: ce1a5af6aeb8
Create Date: 2026-05-22 19:47:09.885973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8360c35958'
down_revision: Union[str, None] = 'ce1a5af6aeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('vendor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'vendor')
    # ### end Alembic commands ###
