"""use_json_for_settings

Revision ID: 85042d3f8c37
Revises: 4d1b42ccc2b8
Create Date: 2026-05-19 14:34:27.445380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85042d3f8c37'
down_revision: Union[str, None] = '4d1b42ccc2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
