"""add_wallets_and_numeric

Revision ID: 9ee8c4416213
Revises: d63a78da20ce
Create Date: 2026-05-23 09:44:41.269269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee8c4416213'
down_revision: Union[str, None] = 'd63a78da20ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'expenses', 'wallets', ['wallet_id'], ['id'])
    op.add_column('incomes', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.alter_column('incomes', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'incomes', 'wallets', ['wallet_id'], ['id'])
    op.add_column('transfers', sa.Column('wallet_from_id', sa.Integer(), nullable=True))
    op.add_column('transfers', sa.Column('wallet_to_id', sa.Integer(), nullable=True))
    op.alter_column('transfers', 'amount_from',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('transfers', 'amount_to',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'transfers', 'wallets', ['wallet_from_id'], ['id'])
    op.create_foreign_key(None, 'transfers', 'wallets', ['wallet_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.alter_column('transfers', 'amount_to',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transfers', 'amount_from',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('transfers', 'wallet_to_id')
    op.drop_column('transfers', 'wallet_from_id')
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.alter_column('incomes', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('incomes', 'wallet_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('expenses', 'wallet_id')
    # ### end Alembic commands ###
