"""add_is_approved_to_user

Revision ID: ce1a5af6aeb8
Revises: fb0969acb962
Create Date: 2026-05-22 19:22:04.792964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1a5af6aeb8'
down_revision: Union[str, None] = 'fb0969acb962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.execute("UPDATE users SET is_approved = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
