"""add_project_to_expense

Revision ID: d63a78da20ce
Revises: 5b8360c35958
Create Date: 2026-05-22 20:13:28.688493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_project_to_expense

Revision ID: d63a78da20ce
Revises: 5b8360c35958
Create Date: 2026-05-22 20:13:28.688493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63a78da20ce'
down_revision: Union[str, None] = '5b8360c35958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('project', sa.String(), nullable=True))
    op.execute("UPDATE expenses SET project = 'Operations'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'project')
    # ### end Alembic commands ###
