"""add_color_icon_type_to_category

Revision ID: fb0969acb962
Revises: 54a181fe20f9
Create Date: 2026-05-22 18:45:54.264781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0969acb962'
down_revision: Union[str, None] = '54a181fe20f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('color', sa.String(), server_default='#9E9E9E', nullable=False))
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('type', sa.String(), server_default='expense', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'color')
    # ### end Alembic commands ###
